before_script:
  - "export DISPLAY=:99.0"
  - "export PATH=~/bin:$PATH"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
gemfile:
  - Gemfile
  - ci/Gemfile.capybara1-0
  - ci/Gemfile.capybara1-1
